// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gatokqijjrxzrrhzmpyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdG9rcWlqanJ4enJyaHptcHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjI2NzYsImV4cCI6MjA2MzgzODY3Nn0.99q61x-mNdzSoLxojeEHVvJm4lzDWVUlerdb5QvQzlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);